# Generated by Django 6.1 on 2026-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('branding', 'Branding & Logo'), ('printing', 'Printing')], db_index=True, max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='portfolio_a_categor_0a0276_idx')],
            },
        ),
    ]
