# Generated by Django 6.1 on 2026-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('custom_apparel', 'Custom Apparel'), ('graphic_design', 'Graphic Design'), ('logo_design', 'Logo Design'), ('card_design', 'Card / Letter Design'), ('printing', 'Printing Service')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='inquiries/')),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('quoted', 'Quoted'), ('completed', 'Completed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Custom inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
