# Generated by Django 6.1 on 2026-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Hiroshyma.Oyk', max_length=100)),
                ('address', models.CharField(default='Nairobi CBD, Kenya', max_length=255)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.TextField(blank=True, default='Mon - Sat: 9:00 AM - 7:00 PM\nSunday: Closed', help_text="One schedule line per row, e.g. 'Mon - Fri: 9am - 6pm'")),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
